---
# Global Common Configuration
project_name: "secure-phpmyadmin-access"
domain_base: "demo.okay.cm"
email: "admin@{{ domain_base }}"
pma_url: "pma.{{ domain_base }}"
jenkins_url: "jenkins.{{ domain_base }}"
auth_url: "auth.{{ domain_base }}"
sonar_url: "sonar.{{ domain_base }}"
nginx_http_port: 80
nginx_https_port: 443
mariadb_version: "11.2"
keycloak_admin_user: "admin"
pma_user: "pma_admin"
mbaapoh_user: "mbaapoh"

# Hybrid Routing Topology (Used if deploying across multiple hosts, or using Nginx)
keycloak_backend_ip: "{{ hostvars[groups['iam_keycloak'][0]]['ansible_host'] | default('127.0.0.1') }}"
oauth2proxy_backend_ip: "{{ hostvars[groups['oauth2_proxy'][0]]['ansible_host'] | default('127.0.0.1') }}"
pma_backend_ip: "{{ hostvars[groups['app_pma'][0]]['ansible_host'] | default('127.0.0.1') }}"
jenkins_backend_ip: "{{ hostvars[groups['app_jenkins'][0]]['ansible_host'] | default('127.0.0.1') }}"

# Gateway Integration Parameters
traefik_network: "fintech-net"
traefik_certresolver: "myresolver"

# Keycloak Core Integration Settings
keycloak_realm: "infrastructure"
keycloak_client_id: "pma-secure-client"
jenkins_client_id: "jenkins-secure-client"




