sonar.projectKey=fintech-customer-web
sonar.projectName=Fintech - Customer Web
sonar.sources=src
sonar.exclusions=**/*.js,**/*.jsx,node_modules/**,build/**,coverage/**,odc-reports/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true
