@Library('fintech-shared-library') _

pipeline {
    agent any
    stages {
        stage('Sync API Contracts') {
            steps {
                syncMicrocksApi(
                    specs: 'projects/api-mocking/api-specs/mtn-momo-collections-v1.yaml:true'
                )
                syncMicrocksApi(
                    specs: 'projects/api-mocking/api-specs/cart-api.yaml:true'
                )
            }
        }
    }
}
