sonar.projectKey=fintech-identity-service
sonar.projectName=Fintech - Identity Service
sonar.sources=.
sonar.exclusions=**/*.js,**/*.jsx,node_modules/**,coverage/**,build/**,dist/**,.npm/**,odc-reports/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true
