spring.data.mongodb.uri=mongodb://mongodb:27017/microcks

keycloak.auth-server-url=http://microcks:8180/auth
keycloak.realm=microcks
keycloak.resource=microcks-app-js
keycloak.bearer-only=true

microcks.serviceaccount=microcks-serviceaccount
microcks.serviceaccount.credentials=ab54d329-e435-41ae-a900-ec6b3fe15c54
