---
- name: Create PMA app directory
  file:
    path: /opt/devops-pma-secure/pma
    state: directory
    mode: '0755'

- name: Template pma docker-compose
  template:
    src: pma-compose.yml.j2
    dest: /opt/devops-pma-secure/pma/docker-compose.yml

- name: Deploy PMA Stack
  community.docker.docker_compose_v2:
    project_src: /opt/devops-pma-secure/pma
    state: present
    pull: always
    remove_orphans: true
