sonar.projectKey=fintech-ledger-api
sonar.projectName=Fintech - Ledger API
sonar.sources=.
sonar.go.file.suffixes=.go
sonar.exclusions=**/*_test.go, .go-cache/**, vendor/**, node_modules/**, build/**, coverage/**, odc-reports/**
sonar.go.coverage.reportPaths=coverage.out
sonar.qualitygate.wait=true
