---
- name: Configure IAM Identity Provider (Keycloak)
  hosts: iam_keycloak
  gather_facts: yes
  become: yes

  vars_files:
    - ../group_vars/all/common.yml
    - ../group_vars/all/configure_keycloak.yml
    - ../group_vars/all/vault.yml

  roles:
    - role: configure_keycloak
