sonar.projectKey=fintech-payment-gateway
sonar.projectName=Fintech - Payment Gateway
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.qualitygate.wait=true
