---
- import_playbook: playbooks/configure_nginx.yml
- import_playbook: playbooks/deploy_traefik.yml
- import_playbook: playbooks/deploy_keycloak.yml
- import_playbook: playbooks/configure_keycloak.yml
- import_playbook: playbooks/deploy_jenkins.yml
- import_playbook: playbooks/deploy_microcks.yml
- import_playbook: playbooks/configure_microcks.yml
- import_playbook: playbooks/deploy_oauth2proxy.yml
- import_playbook: playbooks/deploy_pma.yml
- import_playbook: playbooks/configure_keycloak_users.yml
- import_playbook: playbooks/deploy_sonarqube.yml
- import_playbook: playbooks/configure_keycloak_rbac.yml
