---
- name: Create app directories
  file:
    path: "/opt/devops-pma-secure/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - keycloak
    - pma
    - jenkins

- name: Template keycloak docker-compose
  template:
    src: keycloak-compose.yml.j2
    dest: /opt/devops-pma-secure/keycloak/docker-compose.yml

- name: Template pma docker-compose
  template:
    src: pma-compose.yml.j2
    dest: /opt/devops-pma-secure/pma/docker-compose.yml

- name: Template jenkins docker-compose
  template:
    src: jenkins-compose.yml.j2
    dest: /opt/devops-pma-secure/jenkins/docker-compose.yml

- name: Tear down old monolith stack (cleanup)
  community.docker.docker_compose_v2:
    project_src: /opt/devops-pma-secure
    state: absent
  ignore_errors: true

- name: Deploy Keycloak Stack
  community.docker.docker_compose_v2:
    project_src: /opt/devops-pma-secure/keycloak
    state: present
    pull: always
    remove_orphans: true

- name: Wait for Keycloak port open
  wait_for:
    host: 127.0.0.1
    port: 8080
    timeout: 300

- name: Deploy PMA Stack
  community.docker.docker_compose_v2:
    project_src: /opt/devops-pma-secure/pma
    state: present
    pull: always
    remove_orphans: true

- name: Deploy Jenkins Stack
  community.docker.docker_compose_v2:
    project_src: /opt/devops-pma-secure/jenkins
    state: present
    pull: always
    remove_orphans: true
